name: Ubuntu (RISCV64)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-UbuntuRiscV64
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - name: Run QEMU Docker container
        uses: docker://ghcr.io/amyspark/ubuntu-server:riscv64-23.10
        with:
          args: >
            bash -c
            "uname -a && cat /etc/os-release && pwd && ls -la &&
            sed -i 's|http://ports.ubuntu.com/ubuntu-ports|http://old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list && apt-get update &&

            apt-get install -y build-essential unzip &&
            curl -fsSL https://xmake.io/shget.text | bash &&
            gcc --version &&
            g++ -o mainexe main.cpp &&
            ls -la"


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mainexe
          path: mainexe
