name: Ubuntu (RISCV)

on:
  pull_request:
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-UbuntuArm
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://ghcr.io/amyspark/ubuntu-server:riscv64-23.10
        with:
          args: >
            bash -c
            "uname -a && cat /etc/os-release &&
            add-apt-repository -y ppa:ubuntu-toolchain-r/test && apt-get update &&
            apt update && apt install -y build-essential unzip &&
            cd /github/workspace &&
            g++ main.cpp"
